const EMBED_COLORS = { default: 0x6FA8DC }
const MONEY_MULTIPLIER = 5
const HERO_PORCENTAGE = 1.2
const XP_MULTIPLIER = 10

export {
  EMBED_COLORS,
  MONEY_MULTIPLIER,
  HERO_PORCENTAGE,
  XP_MULTIPLIER
}
