version: "3.8"

services:
  # fix replica set for mongo neded for prisma
  mongo:
    image: mongo
    container_name: lilicas-mongo-main
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - lilicas-local
    healthcheck:
      test: echo 'rs.initiate().ok' | mongo mongo:27017/lilicas --quiet
      interval: 10s
      start_period: 10s
    command: [ "--replSet", "dbrs", "--bind_ip_all" ]

  redis:
    image: redis
    container_name: lilicas-redis
    ports:
      - "6379:6379"
    networks:
      - lilicas-local

  lilicas-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=api
    container_name: lilicas-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - DATABASE_URI=mongodb://mongo:27017/lilicas
      - REDIS_URI=redis://redis:6379
    networks:
      - lilicas-local

  # lilicas-web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=web
  #   container_name: lilicas-web
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - lilicas-api
  #   networks:
  #     - lilicas-local

  # lilicas-bot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=bot
  #   container_name: lilicas-bot
  #   depends_on:
  #     - lilicas-api
  #   networks:
  #     - lilicas-local

networks:
  lilicas-local:
    driver: bridge
