version: "3.8"

services:
  postgres:
    image: postgres
    profiles:
      - dev
      - production
    container_name: lilicas-postgres
    ports:
      - "5432:5432"
    networks:
      - lilicas-local
    environment:
      - POSTGRES_USER=lilicas
      - POSTGRES_PASSWORD=lilicas
      - POSTGRES_DB=lilicas

  redis:
    image: redis
    profiles:
      - dev
      - production
    container_name: lilicas-redis
    ports:
      - "6379:6379"
    networks:
      - lilicas-local

  pg-admin:
    image: dpage/pgadmin4
    profiles:
      - dev
    container_name: lilicas-pg-admin
    ports:
      - "5050:80"
    networks:
      - lilicas-local
    environment:
      - PGADMIN_DEFAULT_EMAIL=local@email.com
      - PGADMIN_DEFAULT_PASSWORD=123
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  lilicas-api:
    profiles:
      - production
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=api
    container_name: lilicas-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URI=postgres://lilicas:lilicas@postgres:5432/lilicas
      - REDIS_URI=redis://redis:6379
    networks:
      - lilicas-local

  # lilicas-web:
  #   profiles:
  #     - production
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=web
  #   container_name: lilicas-web
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - lilicas-api
  #   networks:
  #     - lilicas-local

  # lilicas-bot:
  #   profiles:
  #     - production
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=bot
  #   container_name: lilicas-bot
  #   depends_on:
  #     - lilicas-api
  #   networks:
  #     - lilicas-local

networks:
  lilicas-local:
    driver: bridge
