version: "3.8"

services:
  cockroach:
    image: cockroachdb/cockroach:v23.1.9
    profiles:
      - dev
      - production
    container_name: lilicas-cockroach
    ports:
      - "26257:26257"
      - "8081:8080"
    networks:
      - lilicas-local
    environment:
      - COCKROACH_DATABASE=lilicas
      - COCKROACH_USER=lilicas
      - COCKROACH_PASSWORD=lilicas
    volumes:
      - ./data/cockroach:/cockroach/cockroach-data
    command: start-single-node --insecure

  redis:
    image: redis
    profiles:
      - dev
      - production
    container_name: lilicas-redis
    ports:
      - "6379:6379"
    networks:
      - lilicas-local

  lilicas-api:
    profiles:
      - production
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=api
    container_name: lilicas-api
    ports:
      - "3000:3000"
    depends_on:
      - cockroach
      - redis
    environment:
      - DATABASE_URI=postgres://lilicas:lilicas@postgres:5432/lilicas
      - REDIS_URI=redis://redis:6379
    networks:
      - lilicas-local

  # lilicas-web:
  #   profiles:
  #     - production
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=web
  #   container_name: lilicas-web
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - lilicas-api
  #   networks:
  #     - lilicas-local

  # lilicas-bot:
  #   profiles:
  #     - production
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=bot
  #   container_name: lilicas-bot
  #   depends_on:
  #     - lilicas-api
  #   networks:
  #     - lilicas-local

networks:
  lilicas-local:
    driver: bridge
